### ISSUE TITLE
missing object

### ISSUE THREAD

**Issue by dadnidhi** [worldsproject/android-jigsaw-puzzle-library#1]
In this project of jigsaw puzzle there is some object named as "R".
Can the developer please help me in providing that particular object since i'm not able to find that particular object in the entire file.
I am a student and will be pleased with your help in my learning of android.

**Comment by atrus6** [comment]
R is the auto generated class created by Android. I would recommend reading http://developer.android.com/training/basics/firstapp/index.html as a good first step in learning Android.

**Comment by dadnidhi** [comment]
although it's an auto generated class but few variables are not present as of how to use the variables of "raw" folder which is folder of images but its integer instances with folder name is being used but they are showing error

**Comment by dadnidhi** [comment]
many variables are referred from R but those variables are not present there. what to do about them.

**Comment by atrus6** [comment]
Assuming that you mean the errors are in Mask.java? 

My first suggestion would be to do Project > Clean (again assuming that you're using Eclipse) 

If you could, would you please show me what the errors are so I am able to give you better answers and solutions.

**Comment by dadnidhi** [comment]
variables not found r.java

**Comment by dadnidhi** [comment]
All issues have been sorted. 
some classes were deprecated so i added supression warning but still the project is not running. There are no warnings and no errors in the project but still its not running

**Comment by dadnidhi** [comment]
the type gallery deprecated

**Comment by atrus6** [comment]
Yes, gallery is deprecated.

This is a library, there is nothing to run. To create an app with it:
- Create a new android project
- Add the puzzle library as a library to your new project
  - In eclipse this can be done by right clicking on your new project, Properties > Android and adding puzzle library

**Comment by dadnidhi** [comment]
can u brief me various steps to make project working....please

**Comment by atrus6** [comment]
So, you have the puzzle library as an eclipse project, and it's built all properly, with no errors.
1. Mark the project as a library
   - Right click on the puzzle library.
   - Click properties
   - Go to Android. 
   - Scroll Down and check "Is Library"
2. Create a new application. This will be your future puzzle app.
   - File > Other
   - New Android Application
   - Give it a name, such as "MyPuzzle"
   - Build SDK should be API 16 and minimum SDK should be API 8
   - Click next until you can click finish.
3. Tie in the Puzzle Library to your new app.
   - Right click on MyPuzzle
   - Click properties
   - Go to Android
   - Click Add...
   - Select the puzzle library.
   - Click Okay
4. Add new images for your puzzle
   - Create a new folder in res called "drawable-nodpi"
   - Add your puzzle images to this folder.
   - As an example we will use "image1" and "image2"
5. Edit MainActivity to create the puzzle.
   - Delete the created method onCreateOptionsMenu
   - Your onCreate method should look like:

``` Java
super.onCreate(savedInstanceState);

    int[] mImageIds = { R.drawable.image1, R.drawable.image2, };

    Intent intent = new Intent(this, PuzzleSelectActivity.class);
    intent.putExtra("images", mImageIds);

    this.startActivity(intent);
```
1. And you should add the following to your manifest:

``` Java
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

<activity android:name="org.worldsproject.puzzle.PuzzleSolveActivity" >
</activity>

<activity android:name="org.worldsproject.puzzle.PuzzleSelectActivity" >
</activity>
```

You should be able to run MyPuzzle and it will display the two images as available puzzles.

**Comment by dadnidhi** [comment]
thank you very much for this help.

I've performed all the steps as per the sequence and manner you described here but the application is still not running .
there are no errors but it's not running on the emulator.
i've checked the emulator with other applications it's working.

on emulator its showing application stopped working

**Comment by atrus6** [comment]
What is the error? You can see the exact error in logcat.

If you don't have logcat open, or don't know how to open it, you can open it with 
1. Window > Show View > Other...
2. Android > Logcat

I'm not going to be able to tell you want did, or did not go wrong without some error information :)

**Comment by dadnidhi** [comment]
thank you very very much without your help running this code would not be possible....
it's been a great help for me....

**Comment by dadnidhi** [comment]
how can i reduce the no. of slices in the three levels..

**Comment by atrus6** [comment]
The easiest way is to simply make the source image smaller.

**Comment by dadnidhi** [comment]
but the size of slices still remains small.
have to increase the size of slices. tried changing the difficulty.java file but no changes reflected

**Comment by atrus6** [comment]
If you decrease the source image, then each piece will be a larger portion
of the image.

Unless you're talking about screen size, then you could increase the zoom?

**Comment by dadnidhi** [comment]
I am trying to understand the logic applied but it's very confusing. if you have any file that can help.me in understanding the logic applied please upload it asap

**Comment by anandrajan17** [comment]
hello i cant able to find the library to add when i want to add the code into my new project help me ??

**Comment by atrus6** [comment]
Simply cloning the repo will give you the library.

**Comment by anandrajan17** [comment]
yes i got the library fixed up i rectified all the errors now its giving me a error that android library projects cannot be launched??

**Comment by atrus6** [comment]
It's a library. It is not a standalone app. You use it too add puzzles to a
new app.

**Comment by anandrajan17** [comment]
and is this code used to split images into jigsaw ????or just split images into rectangle shaped once?

**Comment by anandrajan17** [comment]
yes i have added the puzzle activity followed all ur steps and yet inside puzzle activity i got the error R.build when i try to import R which is the only  solution given by eclipse and it wont work??

**Comment by anandrajan17** [comment]
i still havent figured out what to do i am unable to rectify the errors in the puzzle activty which i downloaded from here??

**Comment by atrus6** [comment]
Yes this splits images into jigsaw shapes.

What step are you getting the R error. Have you tried project > Clean in
eclipse?

**Comment by anandrajan17** [comment]
yes i have tried still the same error in all the R in the entire codes??and i have got error in android manifest @sherlock ??

**Comment by anandrajan17** [comment]
d u have a full working code for it??

**Comment by atrus6** [comment]
I do have several apps that use it. I will send you a working eclipse
project tomorrow morning.

**Comment by anandrajan17** [comment]
ok thank u s much yet i need nly a simple app which can split images into jigsaw and rearrange it back to finish the game its for my academic project well waiting for ur code or can u just tell me how to split image into jig saw will do for me?!! thank you

**Comment by anandrajan17** [comment]
well when will u be sending me a code??

**Comment by atrus6** [comment]
​
 Christmas Puzzle.tar.gzhttps://docs.google.com/file/d/0B12GYOHiDx9WNEFlV1ZXTWJyMTQ/edit?usp=drive_web
​

Tim Butram

**Comment by anandrajan17** [comment]
thank u tim i just saw ur mail trying to download the code hope it works fine

**Comment by atrus6** [comment]
This contains just the Christmas puzzle app. Actionbarsherlock and
HoloEverywhere are separate items, but you should have them already.

**Comment by anandrajan17** [comment]
how d i get holoeverywhere and actionbarsherlock??

**Comment by atrus6** [comment]
Search for both of them. Both give instructions on how to add them to a
project.

**Comment by anandrajan17** [comment]
will i be getting it in google itself??

**Comment by atrus6** [comment]
Yes use Google.

**Comment by anandrajan17** [comment]
the app is downloaded there is only one Mainactivity??should i include ur previous coding puzzle library??

**Comment by atrus6** [comment]
No. Everything should be included.

**Comment by anandrajan17** [comment]
everything in the sense??the puzzleactivity master library should be included as a library or should i copy paste all the activity into the cristmazzpuzzle?

**Comment by atrus6** [comment]
It should be included as a library.

**Comment by dieg1** [comment]
hi atrus6, can you please help me with the puzzle library? it has an error with regards to  android:theme="@style/Holo.Theme.Sherlock">

**Comment by anandrajan17** [comment]
hi dieg1, 
you need t include the holoeverywhere library and actionsherlock library

**Comment by ghost** [comment]
yes getting error wherever there is reference for 'R'

**Comment by rameshpolimeni** [comment]
where it is replaced code like (PuzzleSelectActivity or PuzzleSolveActivity)

super.onCreate(savedInstanceState);
int[] mImageIds = { R.drawable.image1, R.drawable.image2, };
Intent intent = new Intent(this, PuzzleSelectActivity.class);
intent.putExtra("images", mImageIds);
this.startActivity(intent);
